/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [`components/**/*.{vue,js}`, `layouts/**/*.vue`, `pages/**/*.vue`, `composables/**/*.{js,ts}`, `plugins/**/*.{js,ts}`, `App.{js,ts,vue}`, `app.{js,ts,vue}`],
  theme: {
    extend: {
      typography: ({ theme }) => ({
        copper: {
          css: {
            "--tw-prose-body": theme("colors.copper[800]"),
            "--tw-prose-headings": theme("colors.copper[900]"),
            "--tw-prose-lead": theme("colors.copper[700]"),
            "--tw-prose-links": theme("colors.copper[900]"),
            "--tw-prose-bold": theme("colors.copper[900]"),
            "--tw-prose-counters": theme("colors.copper[600]"),
            "--tw-prose-bullets": theme("colors.copper[400]"),
            "--tw-prose-hr": theme("colors.copper[300]"),
            "--tw-prose-quotes": theme("colors.copper[900]"),
            "--tw-prose-quote-borders": theme("colors.copper[300]"),
            "--tw-prose-captions": theme("colors.copper[700]"),
            "--tw-prose-code": theme("colors.copper[900]"),
            "--tw-prose-pre-code": theme("colors.copper[100]"),
            "--tw-prose-pre-bg": theme("colors.copper[900]"),
            "--tw-prose-th-borders": theme("colors.copper[300]"),
            "--tw-prose-td-borders": theme("colors.copper[200]"),
            "--tw-prose-invert-body": theme("colors.copper[200]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-lead": theme("colors.copper[300]"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.copper[400]"),
            "--tw-prose-invert-bullets": theme("colors.copper[600]"),
            "--tw-prose-invert-hr": theme("colors.copper[700]"),
            "--tw-prose-invert-quotes": theme("colors.copper[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.copper[700]"),
            "--tw-prose-invert-captions": theme("colors.copper[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-pre-code": theme("colors.copper[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.copper[600]"),
            "--tw-prose-invert-td-borders": theme("colors.copper[700]"),
          },
        },
        "purple-heart": {
          css: {
            "--tw-prose-body": theme("colors.purple-heart[800]"),
            "--tw-prose-headings": theme("colors.purple-heart[900]"),
            "--tw-prose-lead": theme("colors.purple-heart[700]"),
            "--tw-prose-links": theme("colors.purple-heart[900]"),
            "--tw-prose-bold": theme("colors.purple-heart[900]"),
            "--tw-prose-counters": theme("colors.purple-heart[600]"),
            "--tw-prose-bullets": theme("colors.purple-heart[400]"),
            "--tw-prose-hr": theme("colors.purple-heart[300]"),
            "--tw-prose-quotes": theme("colors.purple-heart[900]"),
            "--tw-prose-quote-borders": theme("colors.purple-heart[300]"),
            "--tw-prose-captions": theme("colors.purple-heart[700]"),
            "--tw-prose-code": theme("colors.purple-heart[900]"),
            "--tw-prose-pre-code": theme("colors.purple-heart[100]"),
            "--tw-prose-pre-bg": theme("colors.purple-heart[900]"),
            "--tw-prose-th-borders": theme("colors.purple-heart[300]"),
            "--tw-prose-td-borders": theme("colors.purple-heart[200]"),
            "--tw-prose-invert-body": theme("colors.purple-heart[200]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-lead": theme("colors.purple-heart[300]"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.purple-heart[400]"),
            "--tw-prose-invert-bullets": theme("colors.purple-heart[600]"),
            "--tw-prose-invert-hr": theme("colors.purple-heart[700]"),
            "--tw-prose-invert-quotes": theme("colors.purple-heart[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.purple-heart[700]"),
            "--tw-prose-invert-captions": theme("colors.purple-heart[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-pre-code": theme("colors.purple-heart[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.purple-heart[600]"),
            "--tw-prose-invert-td-borders": theme("colors.purple-heart[700]"),
          },
        },
        "chelsea-cucumber": {
          css: {
            "--tw-prose-body": theme("colors.chelsea-cucumber[800]"),
            "--tw-prose-headings": theme("colors.chelsea-cucumber[900]"),
            "--tw-prose-lead": theme("colors.chelsea-cucumber[700]"),
            "--tw-prose-links": theme("colors.chelsea-cucumber[900]"),
            "--tw-prose-bold": theme("colors.chelsea-cucumber[900]"),
            "--tw-prose-counters": theme("colors.chelsea-cucumber[600]"),
            "--tw-prose-bullets": theme("colors.chelsea-cucumber[400]"),
            "--tw-prose-hr": theme("colors.chelsea-cucumber[300]"),
            "--tw-prose-quotes": theme("colors.chelsea-cucumber[900]"),
            "--tw-prose-quote-borders": theme("colors.chelsea-cucumber[300]"),
            "--tw-prose-captions": theme("colors.chelsea-cucumber[700]"),
            "--tw-prose-code": theme("colors.chelsea-cucumber[900]"),
            "--tw-prose-pre-code": theme("colors.chelsea-cucumber[100]"),
            "--tw-prose-pre-bg": theme("colors.chelsea-cucumber[900]"),
            "--tw-prose-th-borders": theme("colors.chelsea-cucumber[300]"),
            "--tw-prose-td-borders": theme("colors.chelsea-cucumber[200]"),
            "--tw-prose-invert-body": theme("colors.chelsea-cucumber[200]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-lead": theme("colors.chelsea-cucumber[300]"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.chelsea-cucumber[400]"),
            "--tw-prose-invert-bullets": theme("colors.chelsea-cucumber[600]"),
            "--tw-prose-invert-hr": theme("colors.chelsea-cucumber[700]"),
            "--tw-prose-invert-quotes": theme("colors.chelsea-cucumber[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.chelsea-cucumber[700]"),
            "--tw-prose-invert-captions": theme("colors.chelsea-cucumber[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-pre-code": theme("colors.chelsea-cucumber[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.chelsea-cucumber[600]"),
            "--tw-prose-invert-td-borders": theme("colors.chelsea-cucumber[700]"),
          },
        },
        pelorous: {
          css: {
            "--tw-prose-body": theme("colors.pelorous[800]"),
            "--tw-prose-headings": theme("colors.pelorous[900]"),
            "--tw-prose-lead": theme("colors.pelorous[700]"),
            "--tw-prose-links": theme("colors.pelorous[900]"),
            "--tw-prose-bold": theme("colors.pelorous[900]"),
            "--tw-prose-counters": theme("colors.pelorous[600]"),
            "--tw-prose-bullets": theme("colors.pelorous[400]"),
            "--tw-prose-hr": theme("colors.pelorous[300]"),
            "--tw-prose-quotes": theme("colors.pelorous[900]"),
            "--tw-prose-quote-borders": theme("colors.pelorous[300]"),
            "--tw-prose-captions": theme("colors.pelorous[700]"),
            "--tw-prose-code": theme("colors.pelorous[900]"),
            "--tw-prose-pre-code": theme("colors.pelorous[100]"),
            "--tw-prose-pre-bg": theme("colors.pelorous[900]"),
            "--tw-prose-th-borders": theme("colors.pelorous[300]"),
            "--tw-prose-td-borders": theme("colors.pelorous[200]"),
            "--tw-prose-invert-body": theme("colors.pelorous[200]"),
            "--tw-prose-invert-headings": theme("colors.white"),
            "--tw-prose-invert-lead": theme("colors.pelorous[300]"),
            "--tw-prose-invert-links": theme("colors.white"),
            "--tw-prose-invert-bold": theme("colors.white"),
            "--tw-prose-invert-counters": theme("colors.pelorous[400]"),
            "--tw-prose-invert-bullets": theme("colors.pelorous[600]"),
            "--tw-prose-invert-hr": theme("colors.pelorous[700]"),
            "--tw-prose-invert-quotes": theme("colors.pelorous[100]"),
            "--tw-prose-invert-quote-borders": theme("colors.pelorous[700]"),
            "--tw-prose-invert-captions": theme("colors.pelorous[400]"),
            "--tw-prose-invert-code": theme("colors.white"),
            "--tw-prose-invert-pre-code": theme("colors.pelorous[300]"),
            "--tw-prose-invert-pre-bg": "rgb(0 0 0 / 50%)",
            "--tw-prose-invert-th-borders": theme("colors.pelorous[600]"),
            "--tw-prose-invert-td-borders": theme("colors.pelorous[700]"),
          },
        },
      }),
      colors: {
        brand_primary: "#6EA94A",
        brand_secondary: "#5eceeb",
        brand_secondary_saturated: "#5eceeb",
        typography_primary: "#284920",
        background: "#EEF4E5",
        "purple-heart": {
          50: "#eef0ff",
          100: "#e0e4ff",
          200: "#c8ccfd",
          300: "#a6abfb",
          400: "#8482f7",
          500: "#7265ef",
          600: "#6248e3",
          700: "#4c33b8",
          800: "#4531a2",
          900: "#3b2f80",
          950: "#231c4a",
        },
        copper: {
          50: "#faf6f0",
          100: "#f1e5d4",
          200: "#e3caa4",
          300: "#d4ab75",
          400: "#ca9255",
          500: "#b8723d",
          600: "#a95d36",
          700: "#8d4630",
          800: "#74392c",
          900: "#603127",
          950: "#361812",
        },
        denim: {
          50: "#f0f7fe",
          100: "#deedfb",
          200: "#c5e1f8",
          300: "#9ccef4",
          400: "#6eb1ec",
          500: "#4c94e5",
          600: "#3779d9",
          700: "#2a5cb8",
          800: "#2b52a2",
          900: "#284780",
          950: "#1c2d4f",
        },
        sahara: {
          50: "#fafcea",
          100: "#f2f8c9",
          200: "#eaf296",
          300: "#e4eb59",
          400: "#e3e32c",
          500: "#d3cc1f",
          600: "#b8a518",
          700: "#927816",
          800: "#795f1a",
          900: "#684f1b",
          950: "#3c2b0c",
        },
        pelorous: {
          50: "#effcfc",
          100: "#d5f6f8",
          200: "#b0ebf1",
          300: "#7adbe6",
          400: "#3dc2d3",
          500: "#21a5b8",
          600: "#1e859c",
          700: "#1f6c7f",
          800: "#225868",
          900: "#204a59",
          950: "#10313c",
        },
        "chelsea-cucumber": {
          DEFAULT: "#6EA94A",
          50: "#EEF4E5",
          100: "#E2ECD3",
          200: "#C9DCB0",
          300: "#ADCD8C",
          400: "#8EBD69",
          500: "#6EA94A",
          600: "#55893C",
          700: "#3E692E",
          800: "#284920",
          900: "#152912",
          950: "#0D190B",
        },
      },
      fontSize: {
        xxs: "0.5rem",
        xs: "0.75rem",
        sm: "0.875rem",
        base: "1rem",
        lg: "1.125rem",
        highlight: "5rem",
        h1: "4rem",
        h2: "3rem",
        h3: "2rem",
        h4: "1.5rem",
        h5: "1.25rem",
        highlight_sm: "3.5rem",
        h1_sm: "3rem",
        h2_sm: "2.25rem",
        h3_sm: "1.75rem",
        h4_sm: "1.5rem",
        h5_sm: "1.25rem",
      },
      lineHeight: {
        xxs: "0.75rem",
        xs: "1rem",
        sm: "1.25rem",
        base: "1.35rem",
        lg: "1.45rem",
        highlight: "5.5rem",
        h1: "4.25rem",
        h2: "3.25rem",
        h3: "2.25rem",
        h4: "1.75rem",
        h5: "1.5rem",
        highlight_sm: "3.75rem",
        h1_sm: "3.25rem",
        h2_sm: "2.5rem",
        h3_sm: "2rem",
        h4_sm: "1.75rem",
        h5_sm: "1.5rem",
      },
      padding: {
        section_x_sm: "1.5rem",
        section_x: "5rem",
        section_y_sm: "3rem",
        section_y: "5rem",
      },
      spacing: {
        nav: "4rem",
        section_x: "5rem",
      },
    },
  },
  plugins: [require("@tailwindcss/typography")],
};
